name = "EtherParticlesGPU"
uuid = "b4b48745-b42b-4ede-8f73-36871a5e3370"
authors = ["bcynuaa <bcynuaa@163.com>"]
version = "0.1.0"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
julia = "^1.10"
Atomix = "^1.0.1"
KernelAbstractions = "^0.9.31"